import { CONFIG } from "../config";
import type { MemoryItem } from "../domain/schema";
import { guardXmlPayload } from "../infrastructure/guardrail";
import { truncateWords } from "../infrastructure/sanitize";

export interface MarkerSet {
  error: boolean;
  stack: boolean;
  command: boolean;
}

export interface CompressionFallback {
  reason: string;
  display: string;
  compressed: boolean;
  tokenSaved: number;
}

const ERROR_MARKER_RE =
  /\b(ERROR|FATAL|CRITICAL|FAIL(?:ED)?|PANIC|Exception|Error|Traceback|AssertionError|ENOENT|EACCES)\b|exit code|command not found/;
const STACK_MARKER_RE =
  /\b(?:at\s+)?[\w./-]+\.(?:ts|tsx|js|jsx|py|go|rs):\d+\b|\bTraceback\b|\bCaused by\b/i;
const COMMAND_MARKER_RE = /\b(command|stderr|stdout|exit status|exit code)\b/i;
const GENERATED_RE = /\b(generated|do not edit|auto-generated|autogenerated)\b/i;

export function estimateCompressionTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export function detectCriticalMarkers(text: string): MarkerSet {
  return {
    error: ERROR_MARKER_RE.test(text),
    stack: STACK_MARKER_RE.test(text),
    command: COMMAND_MARKER_RE.test(text),
  };
}

export function hasCriticalMarkers(markers: MarkerSet): boolean {
  return markers.error || markers.stack || markers.command;
}

export function compressionLosesCriticalMarkers(original: string, display: string): boolean {
  if (!CONFIG.compressionSafety.criticalMarkerFallbackEnabled) {
    return false;
  }

  const originalMarkers = detectCriticalMarkers(original);
  if (!hasCriticalMarkers(originalMarkers)) {
    return false;
  }

  const displayMarkers = detectCriticalMarkers(display);
  return (
    (originalMarkers.error && !displayMarkers.error) ||
    (originalMarkers.stack && !displayMarkers.stack) ||
    (originalMarkers.command && !displayMarkers.command)
  );
}

export function compressionFallbackReason(original: string, display: string): string | null {
  const originalTokens = estimateCompressionTokens(original);
  const displayTokens = estimateCompressionTokens(display);

  if (original.trim().length > 0 && display.trim().length === 0) {
    return "empty_display";
  }

  if (displayTokens > originalTokens * CONFIG.compressionSafety.maxCompressionInflationRatio) {
    return "inflated_output";
  }

  if (compressionLosesCriticalMarkers(original, display)) {
    return "critical_marker_loss";
  }

  return null;
}

function pathFromMetadata(item: MemoryItem): string | undefined {
  try {
    const metadata = JSON.parse(item.metadata_json || "{}") as Record<string, unknown>;
    for (const key of ["path", "filePath", "sourcePath", "filename"]) {
      const value = metadata[key];
      if (typeof value === "string" && value.trim()) {
        return value;
      }
    }
  } catch {
    // Ignore malformed metadata.
  }
  return undefined;
}

function hasMinifiedShape(text: string): boolean {
  const lines = text.split("\n").filter(Boolean);
  if (lines.length === 0) {
    return false;
  }
  const veryLongLines = lines.filter((line) => line.length > 500).length;
  return veryLongLines / lines.length > 0.4;
}

export function libraryOrGeneratedReason(item: MemoryItem): string | null {
  const path = pathFromMetadata(item)?.replace(/\\/g, "/").toLowerCase();
  if (path) {
    const matched = CONFIG.compressionSafety.libraryGeneratedPathPatterns.find((pattern) =>
      path.includes(pattern.toLowerCase()),
    );
    if (matched) {
      return `path:${matched}`;
    }
  }

  if (GENERATED_RE.test(item.text.slice(0, 2_000))) {
    return "generated_marker";
  }

  if (hasMinifiedShape(item.text)) {
    return "minified_shape";
  }

  return null;
}

export function buildLibraryGuardDisplay(item: MemoryItem, reason: string): CompressionFallback {
  const fullTokens = estimateCompressionTokens(item.text);
  const path = pathFromMetadata(item);
  const display = [
    `[compression guard: library/generated content omitted; reason=${reason}; retrieve with memory_retrieve("${item.id}")]`,
    path ? `path: ${path}` : "",
    `original: ${item.text.length} chars, ~${fullTokens} tokens`,
  ]
    .filter(Boolean)
    .join("\n");
  const displayTokens = estimateCompressionTokens(display);
  return {
    reason,
    display: guardXmlPayload(display),
    compressed: true,
    tokenSaved: Math.max(0, fullTokens - displayTokens),
  };
}

export function buildSafeFallbackDisplay(item: MemoryItem, reason: string): CompressionFallback {
  const originalTokens = estimateCompressionTokens(item.text);
  const excerpt = truncateWords(item.text, CONFIG.compressionSafety.fallbackExcerptWords);
  const markers = detectCriticalMarkers(item.text);
  const display = [
    `[compression fallback: ${reason}; critical_markers=${
      Object.entries(markers)
        .filter(([, present]) => present)
        .map(([name]) => name)
        .join(",") || "none"
    }; retrieve with memory_retrieve("${item.id}")]`,
    excerpt,
  ].join("\n");
  const displayTokens = estimateCompressionTokens(display);

  return {
    reason,
    display: guardXmlPayload(display),
    compressed: displayTokens < originalTokens,
    tokenSaved: Math.max(0, originalTokens - displayTokens),
  };
}
